name: Komunikacja Techniczna, Akademia Finansów i Biznesu Vistula
title: Bożena's homework
description: This is an example of technical documentation hosted on Github pages, using the Just the Docs Jekyll theme. 
remote_theme: boz-code/just-the-docs

color_scheme: light

aux_links:
  "Source repository on GitHub":
    - "//github.com/boz-code/boz-code.github.io"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "This documentation is Bożena's homework for the Technical Communication course at Vistula University (Warsaw). 